### ISSUE TITLE
[CT-3388] [Feature] Add support for pydantic 2.x

### ISSUE THREAD

**Issue by mgierada** [dbt-labs/dbt-semantic-interfaces#208]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently the dbt-core is pined to pydantic (>=1.10,<2.0). Let's make sure we can use the latest pydantic

The issue seems to be in the `dbt-semantic-interfaces`.

### Who will this benefit?

Everybody with a fairly modern tech stack.

### Are you interested in contributing this feature?

Yes

**Comment by dbeatty10** [comment]
Thanks for raising this @mgierada !

I've transferred this issue here for follow-up. See below on quick notes about Pydantic V1.10 vs. V2.

### [Pydantic V1.10 vs. V2](https://github.com/pydantic/pydantic/blob/f42dc2fe978d88c9d06796e0a1837fe5d0b13507/README.md#pydantic-v110-vs-v2)
 
> Pydantic V2 is a ground-up rewrite that offers many new features, performance improvements, and some breaking changes compared to Pydantic V1.
> 
> If you're using Pydantic V1 you may want to look at the
> [pydantic V1.10 Documentation](https://docs.pydantic.dev/) or,
> [`1.10.X-fixes` git branch](https://github.com/pydantic/pydantic/tree/1.10.X-fixes). Pydantic V2 also ships with the latest version of Pydantic V1 built in so that you can incrementally upgrade your code base and projects: `from pydantic import v1 as pydantic_v1`.

### Location in source code

https://github.com/dbt-labs/dbt-semantic-interfaces/blob/b4c0a8290316a8b9695f735e6a42548445225a64/pyproject.toml#L23

**Comment by QMalcolm** [comment]
First, thank you so much for raising this issue! This was initially raised on [dbt-core](https://github.com/dbt-labs/dbt-core), and it got moved here because this repository (dbt-semantic-interfaces) is what is restricting the available pydantic version in dbt-core. However, we already have an issue tracking this work, https://github.com/dbt-labs/dbt-semantic-interfaces/issues/134, and thus I'm going to close this issue as a duplicate.
